#!/bin/sh
#
# chkconfig: 345 86 16
# description: Freeside daemons

QUEUED_USER=%%%QUEUED_USER%%%

SELFSERVICE_USER=%%%SELFSERVICE_USER%%%
SELFSERVICE_MACHINES="%%%SELFSERVICE_MACHINES%%%"

IF=eth0

#INSTALLSCRIPT/INSTALLSITEBIN from Makefile.PL
PATH="$PATH:/usr/local/bin"
export PATH

[ -r /etc/default/freeside ] && . /etc/default/freeside

case "$1" in
  start)
        # Start daemons.
        echo -n "Starting freeside-queued: "
        freeside-queued $QUEUED_USER
        #export NYTPROF="file=/usr/local/etc/freeside/nytprof.out"
        #PERL5OPT="-d:NYTProf" freeside-queued $QUEUED_USER
        echo "done."

        echo -n "Starting freeside-sqlradius-radacctd: "
        freeside-sqlradius-radacctd $QUEUED_USER
        echo "done."

        echo -n "Starting freeside-prepaidd: "
        freeside-prepaidd $QUEUED_USER
        echo "done."

        for MACHINE in $SELFSERVICE_MACHINES; do
          echo -n "Starting freeside-selfservice-server to $MACHINE: "
          freeside-selfservice-server $SELFSERVICE_USER $MACHINE
          echo "done."
        done

        #ip=`/sbin/ifconfig $IF | grep 'inet addr:' | cut -d: -f2- | cut -d' ' -f1`
        #cp /opt/rt3/etc/RT_SiteConfig.pm.ORIG /opt/rt3/etc/RT_SiteConfig.pm
        #perl -pi -e "s/localhost/$ip/" /opt/rt3/etc/RT_SiteConfig.pm

        ;;
  stop)
        # Stop daemons.
        echo -n "Stopping freeside-queued: "
        kill `cat /var/run/freeside-queued.pid`
        echo "done."

        #and
        killall freeside-queued

        echo -n "Stopping freeside-sqlradius-radacctd: "
        kill `cat /var/run/freeside-sqlradius-radacctd.pid`
        echo "done."

        echo -n "Stopping freeside-prepaidd: "
        kill `cat /var/run/freeside-prepaidd.pid`
        echo "done."

        if [ -e /var/run/freeside-selfservice-server.$SELFSERVICE_USER.pid ]
        then
          echo -n "Stopping (old) freeside-selfservice-server: "
          kill `cat /var/run/freeside-selfservice-server.$SELFSERVICE_USER.pid`
          rm /var/run/freeside-selfservice-server.$SELFSERVICE_USER.pid
        fi

        if [ -z "$SELFSERVICE_MACHINES" ]; then SELFSERVICE_MACHINES='localhost'; fi
        for MACHINE in $SELFSERVICE_MACHINES; do
          echo -n "Stopping freeside-selfservice-server to $MACHINE: "
          kill `cat /var/run/freeside-selfservice-server.$SELFSERVICE_USER.$MACHINE.pid`
          echo "done."
        done

        ;;

  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: freeside {start|stop|restart}"
        exit 1
esac

exit 0

